filter:
    paths: [Model/*]
    excluded_paths: [vendor/*, Tests/*]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor]

